import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {sameOrigin,apiFailure} from '@/lib/access';
import {feedContext,feedRows,validConfig,configId} from '@/lib/bid-evidence';
import {TENANTS} from '@/lib/metrics';
import {createRecord,updateRecord} from '@/lib/records';
import {database,auditStatement} from '@/lib/store';
async function master(){const user=await getChatGPTUser();if(!user)throw new Error('AUTH');if(!env.BID_FEED_MASTER_EMAIL||user.email.toLowerCase()!==env.BID_FEED_MASTER_EMAIL.toLowerCase())throw new Error('ACCESS');return user;}
async function matchesSecret(actual:string,expected:string){if(!expected||expected.length<32||actual.length>300)return false;const digest=async(s:string)=>new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));const [a,b]=await Promise.all([digest(actual),digest(expected)]);let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0;}
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(request:Request){try{const {config,revision,metrics}=await feedContext();if(new URL(request.url).searchParams.get('admin')==='1'){await master();const rows=await feedRows(config,metrics);return reply({config,revision,metrics:metrics.map(m=>({id:m.id,name:m.name,department:m.department,source:m.source})),sites:TENANTS.drpa.sites,eligible:rows.length,serviceReady:!!env.BID_FEED_KEY});}if(!await matchesSecret((request.headers.get('authorization')||'').replace(/^Bearer /,''),env.BID_FEED_KEY||''))return reply({error:'A valid read-only bid-feed credential is required.'},403);if(!config.enabled)return reply({schemaVersion:1,published:false,complete:true,configurationVersion:String(revision),records:[]});const records=await feedRows(config,metrics);if(records.length>40)return reply({error:'More than 40 approved records match. Narrow the published sites, metrics or period before synchronising.'},422);return reply({schemaVersion:1,published:true,complete:true,configurationVersion:String(revision),records});}catch(e){return apiFailure(e);}}
export async function POST(request:Request){try{sameOrigin(request);const user=await master();if(Number(request.headers.get('content-length'))>16000)return reply({error:'Configuration is too large.'},413);const body=await request.json() as any;const current=await feedContext();if(!validConfig(body.config,current.metrics)||!Number.isInteger(body.revision)||body.revision<0)throw new Error('Choose valid periods, metrics and sites, and record your aggregate-data review before publishing.');const config={enabled:body.config.enabled,metricIds:body.config.metricIds,sites:body.config.sites,from:body.config.from,to:body.config.to,attestation:body.config.attestation};if(body.revision!==current.revision)return reply({error:'The feed configuration changed. Reload before saving.'},409);if(config.enabled&&(await feedRows(config,current.metrics)).length>40)throw new Error('Narrow the scope to 40 approved records or fewer.');let results;if(current.revision===0)results=await database().batch([createRecord('drpa','bid_feed_configuration',config,configId),auditStatement('drpa',user.displayName,'Created bid evidence feed','bid-feed','Master selected scope; sample records excluded.')]);else results=await database().batch([updateRecord('drpa','bid_feed_configuration',configId,config,current.revision)]);if(!results[0].meta.changes)return reply({error:'The feed configuration changed. Reload before saving.'},409);return reply({saved:true,revision:current.revision+1});}catch(e){return apiFailure(e);}}
