import {database} from './store';
import {METRICS,TENANTS,calculate,validPeriod,type Metric,type Observation} from './metrics';
import {customMetrics,oneRecord} from './records';
export type FeedConfig={enabled:boolean;metricIds:string[];sites:string[];from:string;to:string;attestation:string};
export const configId='drpa-bid-feed';
export const emptyFeed=():FeedConfig=>({enabled:false,metricIds:[],sites:[],from:new Date().toISOString().slice(0,7),to:new Date().toISOString().slice(0,7),attestation:''});
export async function feedContext(){const record=await oneRecord<FeedConfig>('drpa','bid_feed_configuration',configId);const metrics=[...METRICS,...await customMetrics('drpa')].filter(m=>!m.restricted&&m.department!=='Finance');return {config:record||emptyFeed(),revision:record?record._version:0,metrics};}
export function eligibleForBid(r:Observation,m:Metric,config:FeedConfig){return r.tenant==='drpa'&&r.status==='approved'&&r.version>=1&&Number.isFinite(r.numerator)&&r.numerator>=0&&Number.isFinite(r.denominator)&&r.denominator>=0&&(!['ratio','rate','mean'].includes(m.method)||r.denominator>0)&&validPeriod(r.period)&&r.period>=config.from&&r.period<=config.to&&config.sites.includes(r.site)&&config.metricIds.includes(r.metric)&&(!m.sites?.length||m.sites.includes(r.site))&&r.actor!=='Demo seed'&&!/SAMPLE-|synthetic|demonstration|fictional/i.test(r.source+' '+r.note)&&!!r.source.trim();}
export async function feedRows(config:FeedConfig,metrics:Metric[]){const rows=(await database().prepare("SELECT * FROM observations WHERE tenant='drpa' AND status='approved' AND period>=? AND period<=? ORDER BY period DESC,site,metric").bind(config.from,config.to).all<Observation>()).results;return rows.flatMap(r=>{const m=metrics.find(m=>m.id===r.metric);if(!m||!eligibleForBid(r,m,config))return [];const value=calculate(m,[r]);if(value===null||!Number.isFinite(value))return [];return [{id:r.id,metric:m.id,title:m.name,site:r.site,period:r.period,numerator:r.numerator,denominator:r.denominator,numeratorLabel:m.numeratorLabel,denominatorLabel:m.denominatorLabel,method:m.method,unit:m.unit,value,source:r.source,observationVersion:String(r.version),definitionVersion:m.definitionVersion||'definition-1',updatedAt:r.updated}];});}
export function validConfig(value:any,metrics:Metric[]):value is FeedConfig{return value&&typeof value.enabled==='boolean'&&Array.isArray(value.metricIds)&&value.metricIds.length<=40&&value.metricIds.every((id:unknown)=>typeof id==='string'&&metrics.some(m=>m.id===id))&&new Set(value.metricIds).size===value.metricIds.length&&Array.isArray(value.sites)&&value.sites.length<=TENANTS.drpa.sites.length&&value.sites.every((s:unknown)=>typeof s==='string'&&TENANTS.drpa.sites.includes(s))&&validPeriod(value.from)&&validPeriod(value.to)&&value.from<=value.to&&typeof value.attestation==='string'&&value.attestation.length<=3000&&(!value.enabled||value.metricIds.length&&value.sites.length&&value.attestation.trim().length>=12);}
