import { unzipSync, strFromU8 } from "fflate";
const workerUrl="/vendor/pdf.worker-6.3.289.min.mjs";
function xml(text:string){const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("The document contains invalid XML.");return doc;}
export async function fileText(file:File):Promise<string>{
 if(file.size>5242880)throw new Error("Use a file no larger than 5 MB.");const ext=file.name.split(".").pop()?.toLowerCase();let text="";
 if(ext==="txt"||ext==="csv"){text=await file.text();if(text.includes("\0"))throw new Error("This text file contains binary data.");}
 else if(ext==="pdf"){
  const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;const loading=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())});const pdf=await loading.promise;
  try{if(pdf.numPages>120)throw new Error("This PDF exceeds 120 pages. Use the relevant schedules or paste a focused extract.");const pages:string[]=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();pages.push(`Page ${p}\n`+content.items.map(x=>"str" in x?x.str+(x.hasEOL?"\n":" "):"").join(""));page.cleanup();}text=pages.join("\n\n");if(text.replace(/Page \d+/g,"").trim().length<20)throw new Error("This PDF has no readable text. A scanned file needs OCR or a reviewed text extract.");}finally{await loading.destroy();}
 }else if(ext==="docx"||ext==="xlsx"){
  let total=0;const archive=unzipSync(new Uint8Array(await file.arrayBuffer()),{filter:entry=>{const include=ext==="docx"?entry.name==="word/document.xml":/^xl\/(workbook\.xml|_rels\/workbook\.xml\.rels|sharedStrings\.xml|worksheets\/sheet\d+\.xml)$/.test(entry.name);if(include){total+=entry.originalSize;if(entry.originalSize>20000000||total>40000000)throw new Error("The decompressed document is too large. Import a focused extract.");}return include;}});
  if(ext==="docx"){const main=archive["word/document.xml"];if(!main)throw new Error("This is not a valid DOCX document.");const document=xml(strFromU8(main));text=Array.from(document.getElementsByTagNameNS("*","p")).map(p=>Array.from(p.getElementsByTagNameNS("*","t")).map(t=>t.textContent||"").join("")).filter(Boolean).join("\n");}
  else{if(!archive["xl/workbook.xml"])throw new Error("This is not a valid XLSX workbook.");const shared=archive["xl/sharedStrings.xml"]?Array.from(xml(strFromU8(archive["xl/sharedStrings.xml"])).getElementsByTagNameNS("*","si")).map(si=>si.textContent||""):[];const relationships=archive["xl/_rels/workbook.xml.rels"]?Array.from(xml(strFromU8(archive["xl/_rels/workbook.xml.rels"])).getElementsByTagNameNS("*","Relationship")):[];const sheets=Array.from(xml(strFromU8(archive["xl/workbook.xml"])).getElementsByTagNameNS("*","sheet"));const sections:string[]=[];
   for(const sheet of sheets){const rid=sheet.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id");let target=relationships.find(r=>r.getAttribute("Id")===rid)?.getAttribute("Target")||"";target=target.replace(/^\//,"");if(!target.startsWith("xl/"))target="xl/"+target;const bytes=archive[target];if(!bytes)continue;const rows=Array.from(xml(strFromU8(bytes)).getElementsByTagNameNS("*","row"));if(rows.length>5000)throw new Error("A worksheet exceeds 5,000 rows. Use a focused export.");const output=rows.map(row=>Array.from(row.getElementsByTagNameNS("*","c")).map(c=>{const raw=c.getElementsByTagNameNS("*","v")[0]?.textContent||"";const value=c.getAttribute("t")==="s"?shared[Number(raw)]||"":c.getAttribute("t")==="inlineStr"?c.getElementsByTagNameNS("*","is")[0]?.textContent||"":raw||c.getElementsByTagNameNS("*","f")[0]?.textContent||"";return value?`${c.getAttribute("r")}: ${value}`:"";}).filter(Boolean).join(" | ")).filter(Boolean);sections.push(`Sheet: ${sheet.getAttribute("name")}\n`+output.join("\n"));}text=sections.join("\n\n");}
 }else throw new Error("Choose PDF, DOCX, XLSX, TXT or CSV.");
 if(text.length>100000)throw new Error("The extract exceeds 100,000 characters. Paste the relevant KPI or reporting schedule instead.");if(!text.trim())throw new Error("No readable text was found.");return text;
}
