import { database } from "./store";
import { TENANTS, PERIODS, type TenantId, METRICS, seedRows, type Metric } from "./metrics";
import { assuranceRows, type Contract, type Requirement, type FmtLine } from "./contracts";
export type Stored<T=Record<string,unknown>>=T&{id:string;_version:number};
export async function listRecords<T>(tenant:string,kind:string):Promise<Stored<T>[]>{const r=await database().prepare("SELECT id,payload,version FROM platform_records WHERE tenant=? AND kind=? ORDER BY created").bind(tenant,kind).all<{id:string;payload:string;version:number}>();return r.results.map(x=>({...JSON.parse(x.payload),id:x.id,_version:x.version}));}
export async function oneRecord<T>(tenant:string,kind:string,id:string):Promise<Stored<T>|null>{const r=await database().prepare("SELECT id,payload,version FROM platform_records WHERE tenant=? AND kind=? AND id=?").bind(tenant,kind,id).first<{id:string;payload:string;version:number}>();return r?{...JSON.parse(r.payload),id:r.id,_version:r.version}:null;}
export function createRecord(tenant:string,kind:string,payload:unknown,id=crypto.randomUUID()){const time=new Date().toISOString();return database().prepare("INSERT INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,?,?,1,?,?)").bind(id,tenant,kind,JSON.stringify(payload),time,time);}
export function updateRecord(tenant:string,kind:string,id:string,payload:unknown,version:number){return database().prepare("UPDATE platform_records SET payload=?,version=version+1,updated=? WHERE tenant=? AND kind=? AND id=? AND version=?").bind(JSON.stringify(payload),new Date().toISOString(),tenant,kind,id,version);}
export async function customMetrics(tenant:string):Promise<Metric[]>{const r=await database().prepare("SELECT payload FROM platform_records WHERE tenant=? AND kind='metric'").bind(tenant).all<{payload:string}>();return r.results.map(x=>JSON.parse(x.payload));}
export async function seedAdvanced(tenant:TenantId){
 const found=await database().prepare("SELECT id FROM platform_records WHERE tenant=? AND kind='contract' LIMIT 1").bind(tenant).first();if(found)return;
 const statements:D1PreparedStatement[]=[];const requirements:Requirement[]=[];const contracts:Contract[]=[];
 TENANTS[tenant].sites.forEach((site,i)=>{const id=`sample-contract-${tenant}-${i}`;const c:Contract={id,title:`${site} · example service`,commissioner:"Example commissioning team",service:"Secure primary care · illustration",sites:[site],reference:"SAMPLE-CONTRACT · replace with the signed agreement",version:"Illustration v1",effectiveFrom:"2026-04-01",effectiveTo:"2027-03-31",status:"Example active",note:"Synthetic contract record. No actual contractual threshold, HJIP code or commissioner commitment has been imported."};contracts.push(c);statements.push(database().prepare("INSERT OR IGNORE INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,'contract',?,1,?,?)").bind(id,tenant,JSON.stringify(c),new Date().toISOString(),new Date().toISOString()));
  [["delivery","Contract","EX-KPI-01","Service hours delivered",98,95],["access","HJIP","EX-HJIP-01","Timely reviews · illustrative indicator",95,90],["actions","Contract","EX-KPI-03","Governance actions closed on time",95,85]].forEach((v,j)=>{const r:Requirement={id:`sample-requirement-${tenant}-${i}-${j}`,contractId:id,type:v[1] as Requirement["type"],code:String(v[2]),title:String(v[3]),clause:`Illustration section ${j+1}`,quote:"Sample only. Import the signed contract or current commissioner HJIP guide and validate this mapping before use.",metricId:String(v[0]),target:Number(v[4]),amber:Number(v[5]),frequency:"Monthly",owner:j===1?"Clinical services lead":"Site lead",sourceVersion:"Illustration v1",documentId:"",status:"approved",attribution:"Shared · review the cause",exception:i===2?"Example access constraints require joint review.":"",action:i===2?"Review overdue actions and access exceptions at the service meeting.":"Review any exceptions with the accountable owner.",actionOwner:"Site lead",dueDate:"2026-10-15",shareEvidence:"Illustrative aggregate reconciliation reviewed by the example service owner.",definitionNote:j===1?"This is an illustrative HJIP-style mapping, not an official HJIP identifier or definition.":"Synthetic definition and target."};requirements.push(r);statements.push(database().prepare("INSERT OR IGNORE INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,'requirement',?,1,?,?)").bind(r.id,tenant,JSON.stringify(r),new Date().toISOString(),new Date().toISOString()));});
 });
 const sampleSite=TENANTS[tenant].sites[tenant==="drpa"?2:0];const contract=contracts.find(c=>c.sites.includes(sampleSite))!;const packId=`sample-pack-${tenant}`;const pack={id:packId,contractId:contract.id,contractTitle:contract.title,commissioner:contract.commissioner,site:sampleSite,period:"2026-09",title:"Example commissioner assurance · September",summary:"Fictional review pack showing the assurance workflow. Exceptions and actions accompany the results; missing data is disclosed.",rows:assuranceRows(requirements.filter(r=>r.contractId===contract.id),METRICS,seedRows(tenant),sampleSite,"2026-09"),status:"published",version:1,created:"2026-10-01T09:00:00Z",publishedAt:"2026-10-01T09:00:00Z",approvedBy:"Example reviewer",dataAsOf:"2026-10-01T08:00:00Z",synthetic:true,includedCount:3,totalCount:3};statements.push(database().prepare("INSERT OR IGNORE INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,'pack',?,1,?,?)").bind(packId,tenant,JSON.stringify(pack),pack.created,pack.created));
 if(tenant==="drpa"){
 const site="Manston";const definitions=[['income','Revenue','Recognised service revenue','income',445000,'200'],['staff','Staff Pay','Primary care staff','cost',330000,'400'],['medicines','Non-Pay Clinical','Medicines','cost',16000,'500'],['training','Staff Related Non-Pay','Training / CPD','cost',6500,'610'],['facilities','Facilities','Facilities and service equipment','cost',15000,'650'],['overheads','Other Overheads','Allocated central support','cost',15000,'700'],['escort','Escort & Bedwatch','Escort and bedwatch','cost',3000,'800']];
 for(const d of definitions){const id=`sample-fmt-${d[0]}`;const line:FmtLine={id,site,service:"Example service",group:String(d[1]),name:String(d[2]),type:d[3] as FmtLine['type'],reference:`FMT structure · ${d[1]} · illustrative line`,baselineVersion:"Example FMT v1"};statements.push(database().prepare("INSERT OR IGNORE INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,'fmt_line',?,1,?,?)").bind(id,tenant,JSON.stringify(line),pack.created,pack.created));
 const mapping={id:`sample-map-${d[0]}`,accountCode:String(d[5]),tracking:site,site,lineId:id};statements.push(database().prepare("INSERT OR IGNORE INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,'mapping',?,1,?,?)").bind(mapping.id,tenant,JSON.stringify(mapping),pack.created,pack.created));
 for(const [pi,period] of PERIODS.entries()){const budget={id:`sample-budget-${d[0]}-${period}`,lineId:id,site,period,amount:Number(d[4]),source:"SAMPLE-FMT · explicit monthly profile"};const actual={id:`sample-actual-${d[0]}-${period}`,accountCode:String(d[5]),accountName:String(d[2]),tracking:site,period,amount:Math.round(Number(d[4])*(d[3]==='income'?0.99:d[0]==='staff'?1.04:0.98)*(0.92+pi*0.016)),reference:`SAMPLE-LEDGER-${d[0]}-${period}`,status:"approved",source:"Synthetic ledger · Xero is not connected"};for(const [kind,item] of [["budget",budget],["actual",actual]] as const)statements.push(database().prepare("INSERT OR IGNORE INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,?,?,1,?,?)").bind(item.id,tenant,kind,JSON.stringify(item),pack.created,pack.created));}
 }
 }
 for(let i=0;i<statements.length;i+=70)await database().batch(statements.slice(i,i+70));
}
