import { env } from "cloudflare:workers";
import { database } from "./store";
type XeroEnvironment={XERO_CLIENT_ID?:string;XERO_CLIENT_SECRET?:string;XERO_REDIRECT_URI?:string;XERO_TOKEN_ENCRYPTION_KEY?:string;XERO_SCOPES?:string};
type Tokens={access_token:string;refresh_token:string;expires_at:number};
type Connection={tenantId:string;tenantName:string;id:string};
export function xeroConfig(){const e=env as unknown as XeroEnvironment;return {...e,configured:!!(e.XERO_CLIENT_ID&&e.XERO_CLIENT_SECRET&&e.XERO_REDIRECT_URI&&e.XERO_TOKEN_ENCRYPTION_KEY),scopes:e.XERO_SCOPES||"offline_access accounting.reports.profitandloss.read accounting.settings.read"};}
const encoder=new TextEncoder();
const b64=(bytes:Uint8Array)=>btoa(Array.from(bytes).map(x=>String.fromCharCode(x)).join(""));
const decode=(s:string)=>Uint8Array.from(atob(s),x=>x.charCodeAt(0));
async function encryptionKey(){const raw=xeroConfig().XERO_TOKEN_ENCRYPTION_KEY;if(!raw)throw new Error("The Xero token vault is not configured.");const bytes=decode(raw);if(bytes.length!==32)throw new Error("The Xero token encryption key must contain 32 bytes.");return crypto.subtle.importKey("raw",bytes,"AES-GCM",false,["encrypt","decrypt"]);}
export async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},await encryptionKey(),encoder.encode(JSON.stringify(value)));return b64(iv)+"."+b64(new Uint8Array(cipher));}
export async function unseal<T>(value:string):Promise<T>{const [iv,cipher]=value.split(".");const bytes=await crypto.subtle.decrypt({name:"AES-GCM",iv:decode(iv)},await encryptionKey(),decode(cipher));return JSON.parse(new TextDecoder().decode(bytes));}
export function base64url(bytes:Uint8Array){return b64(bytes).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
export async function saveTokens(tenant:string,owner:string,tokens:Tokens){const encrypted=await seal(tokens);await database().prepare("INSERT INTO integration_vault (id,tenant,owner,provider,encrypted,updated) VALUES (?,?,?,'xero',?,?) ON CONFLICT(tenant,owner,provider) DO UPDATE SET encrypted=excluded.encrypted,updated=excluded.updated").bind(crypto.randomUUID(),tenant,owner,encrypted,new Date().toISOString()).run();}
export async function tokenExchange(parameters:URLSearchParams){const c=xeroConfig();if(!c.configured)throw new Error("Xero is not configured. Your programmer must add the OAuth application and token-vault settings.");const r=await fetch("https://identity.xero.com/connect/token",{method:"POST",headers:{Authorization:"Basic "+btoa(c.XERO_CLIENT_ID+":"+c.XERO_CLIENT_SECRET),"Content-Type":"application/x-www-form-urlencoded"},body:parameters.toString(),signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`Xero authorisation failed (${r.status}). Review the app settings or reconnect.`);const j=await r.json() as {access_token:string;refresh_token:string;expires_in:number};if(!j.access_token||!j.refresh_token)throw new Error("Xero did not return an offline connection. Check the requested scopes.");return {access_token:j.access_token,refresh_token:j.refresh_token,expires_at:Date.now()+j.expires_in*1000};}
export async function accessToken(tenant:string,owner:string){const row=await database().prepare("SELECT encrypted FROM integration_vault WHERE tenant=? AND owner=? AND provider='xero'").bind(tenant,owner).first<{encrypted:string}>();if(!row)throw new Error("Connect your Xero organisation before syncing.");const t=await unseal<Tokens>(row.encrypted);if(t.expires_at>Date.now()+120000)return t.access_token;const next=await tokenExchange(new URLSearchParams({grant_type:"refresh_token",refresh_token:t.refresh_token}));const encrypted=await seal(next);const result=await database().prepare("UPDATE integration_vault SET encrypted=?,updated=? WHERE tenant=? AND owner=? AND provider='xero' AND encrypted=?").bind(encrypted,new Date().toISOString(),tenant,owner,row.encrypted).run();if(result.meta.changes===0){const current=await database().prepare("SELECT encrypted FROM integration_vault WHERE tenant=? AND owner=? AND provider='xero'").bind(tenant,owner).first<{encrypted:string}>();if(!current)throw new Error("Xero connection was removed.");return (await unseal<Tokens>(current.encrypted)).access_token;}return next.access_token;}
async function xeroFetch<T>(token:string,url:string,org?:string):Promise<T>{const r=await fetch(url,{headers:{Authorization:"Bearer "+token,Accept:"application/json",...(org?{"Xero-Tenant-Id":org}:{})},signal:AbortSignal.timeout(45000)});if(!r.ok)throw new Error(r.status===429?"Xero's request limit was reached. Retry after the indicated cooldown.":`Xero read failed (${r.status}). Review the connection and report permissions.`);return await r.json() as T;}
export async function connections(tenant:string,owner:string){return xeroFetch<Connection[]>(await accessToken(tenant,owner),"https://api.xero.com/connections");}
export async function accountingRead<T>(tenant:string,owner:string,org:string,path:string){const orgs=await connections(tenant,owner);if(!orgs.some(x=>x.tenantId===org))throw new Error("This Xero organisation is outside your connection.");return xeroFetch<T>(await accessToken(tenant,owner),"https://api.xero.com/api.xro/2.0/"+path,org);}
export async function xeroStatus(tenant:string,owner:string){const c=xeroConfig();const connection=await database().prepare("SELECT updated FROM integration_vault WHERE tenant=? AND owner=? AND provider='xero'").bind(tenant,owner).first<{updated:string}>();return {configured:c.configured,connected:!!connection,updated:connection?.updated||"",mode:"Read-only account balances",scopes:c.scopes};}
export type XeroAccount={AccountID:string;Code?:string;Name:string};
export type XeroCategory={TrackingCategoryID:string;Name:string;Status:string;Options:Array<{TrackingOptionID:string;Name:string;Status:string}>};
type ReportRow={RowType?:string;Cells?:Array<{Value?:string;Attributes?:Array<{Id?:string;Value?:string}>}>;Rows?:ReportRow[]};
export function reportBalances(report:{Reports?:Array<{Rows?:ReportRow[]}>},accounts:XeroAccount[]){const output:Array<{accountCode:string;accountName:string;amount:number}>=[];function walk(rows:ReportRow[]){for(const row of rows){if(row.Rows)walk(row.Rows);if(row.RowType!=="Row")continue;const cells=row.Cells||[];const accountId=cells.flatMap(c=>c.Attributes||[]).find(a=>a.Id?.toLowerCase()==="account")?.Value;const account=accounts.find(a=>a.AccountID===accountId);if(!account?.Code)continue;const amount=Number(cells[1]?.Value);if(!Number.isFinite(amount))throw new Error("Xero returned an invalid account amount.");output.push({accountCode:account.Code,accountName:account.Name,amount});}}walk(report.Reports?.[0]?.Rows||[]);if(new Set(output.map(x=>x.accountCode)).size!==output.length)throw new Error("Xero returned duplicate account rows. Reconcile the report layout before import.");return output;}
