import { requestScope, requireModule, sameOrigin, apiFailure } from "@/lib/access";
import { xeroConfig, xeroStatus, connections, accountingRead, base64url, seal, reportBalances, type XeroAccount, type XeroCategory } from "@/lib/xero";
import { createRecord, oneRecord } from "@/lib/records";
import { database, auditStatement } from "@/lib/store";
import { validPeriod } from "@/lib/metrics";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const s=await requestScope(request);requireModule(s,"finance");if(!["board","finance"].includes(s.role))throw new Error("ACCESS");const action=s.url.searchParams.get("action");
 if(action==="connect"){sameOrigin(request);const c=xeroConfig();if(!c.configured)throw new Error("Xero is not yet configured. Add the server OAuth application and encryption settings first.");const state=base64url(crypto.getRandomValues(new Uint8Array(32))),verifier=base64url(crypto.getRandomValues(new Uint8Array(32))),challenge=base64url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier))));await database().batch([createRecord(s.tenant,"xero_state",{owner:s.user.id,expires:Date.now()+600000,encrypted:await seal({verifier})},state)]);const url=new URL("https://login.xero.com/identity/connect/authorize");url.search=new URLSearchParams({response_type:"code",client_id:c.XERO_CLIENT_ID!,redirect_uri:c.XERO_REDIRECT_URI!,scope:c.scopes,state,code_challenge:challenge,code_challenge_method:"S256"}).toString();return new Response(null,{status:302,headers:{Location:url.toString(),"Set-Cookie":`xero_oauth_state=${state}; HttpOnly; Secure; SameSite=Lax; Path=/api/xero; Max-Age=600`,"Cache-Control":"no-store"}});}
 if(action==="metadata"){const orgs=await connections(s.tenant,s.user.id);const org=s.url.searchParams.get("org");if(!org)return Response.json({organisations:orgs});const [accounts,tracking]=await Promise.all([accountingRead<{Accounts:XeroAccount[]}>(s.tenant,s.user.id,org,"Accounts"),accountingRead<{TrackingCategories:XeroCategory[]}>(s.tenant,s.user.id,org,"TrackingCategories")]);return Response.json({organisations:orgs,accounts:accounts.Accounts,tracking:tracking.TrackingCategories.filter(c=>c.Status==="ACTIVE")},{headers:{"Cache-Control":"no-store"}});}
 return Response.json(await xeroStatus(s.tenant,s.user.id),{headers:{"Cache-Control":"no-store"}});
 }catch(e){return apiFailure(e);}}
export async function POST(request:Request){try{const s=await requestScope(request);requireModule(s,"finance");sameOrigin(request);if(!["board","finance"].includes(s.role))throw new Error("ACCESS");const b=await request.json() as {organisation:string;category:string;option:string;period:string};if(!validPeriod(b.period))throw new Error("Select an available month.");const {TrackingCategories:categories}=await accountingRead<{TrackingCategories:XeroCategory[]}>(s.tenant,s.user.id,b.organisation,"TrackingCategories");const category=categories.find(c=>c.TrackingCategoryID===b.category&&c.Status==="ACTIVE"),option=category?.Options.find(o=>o.TrackingOptionID===b.option&&o.Status==="ACTIVE");if(!option)throw new Error("Choose an active tracking category and option for this service.");const bindingId="xero-org-"+s.tenant;const binding=await oneRecord<{organisation:string;category:string}>(s.tenant,"xero_organisation",bindingId);if(binding&&(binding.organisation!==b.organisation||binding.category!==b.category))throw new Error("This provider workspace already uses another Xero organisation or tracking category. Review the accounting scope before changing it.");if(!binding)await database().batch([createRecord(s.tenant,"xero_organisation",{organisation:b.organisation,category:b.category},bindingId)]);const {Accounts:accounts}=await accountingRead<{Accounts:XeroAccount[]}>(s.tenant,s.user.id,b.organisation,"Accounts");const [year,month]=b.period.split("-").map(Number);const from=b.period+"-01",to=b.period+"-"+new Date(Date.UTC(year,month,0)).getUTCDate();const params=new URLSearchParams({fromDate:from,toDate:to,trackingCategoryID:b.category,trackingOptionID:b.option,cashBasis:"false",standardLayout:"true"});const report=await accountingRead<Parameters<typeof reportBalances>[0]>(s.tenant,s.user.id,b.organisation,"Reports/ProfitAndLoss?"+params);const balances=reportBalances(report,accounts);if(!balances.length||balances.length>100)throw new Error("The service report contains no importable rows or exceeds 100 account balances. Review the report configuration.");const statements:D1PreparedStatement[]=[];
 for(const a of balances){const grain=[s.tenant,a.accountCode,option.Name,b.period].join("|");const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(grain));const found=await database().prepare("SELECT id FROM platform_records WHERE tenant=? AND kind='actual' AND json_extract(payload,'$.accountCode')=? AND json_extract(payload,'$.tracking')=? AND json_extract(payload,'$.period')=?").bind(s.tenant,a.accountCode,option.Name,b.period).first<{id:string}>();const targetId=found?.id||"ledger-"+Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,"0")).join("");const old=await oneRecord(s.tenant,"actual",targetId),id=crypto.randomUUID();statements.push(database().prepare("UPDATE platform_records SET payload=json_set(payload,'$.status','superseded'),version=version+1,updated=? WHERE tenant=? AND kind='actual_pending' AND json_extract(payload,'$.targetId')=? AND json_extract(payload,'$.status')='pending'").bind(new Date().toISOString(),s.tenant,targetId));statements.push(createRecord(s.tenant,"actual_pending",{...a,id,targetId,baseVersion:old?._version||0,tracking:option.Name,period:b.period,reference:`Xero organisation ${b.organisation} · P&L ${from}–${to} · tracking ${category!.Name}/${option.Name}`,status:"pending",source:"Xero · accrual P&L account balances",created:new Date().toISOString()},id));}
 statements.push(auditStatement(s.tenant,s.user.id,"Xero balances staged",crypto.randomUUID(),JSON.stringify({period:b.period,tracking:option.Name,rows:balances.length,rolePreview:s.role})));await database().batch(statements);return Response.json({ok:true,count:balances.length},{headers:{"Cache-Control":"no-store"}});
 }catch(e){return apiFailure(e);}}
