import assert from "node:assert/strict";
import { readFile, writeFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import ts from "typescript";

const root=fileURLToPath(new URL("../",import.meta.url));
const temp=await mkdtemp(join(tmpdir(),"drpa-domain-checks-"));
let count=0;
const check=(label,fn)=>{fn();count++;process.stdout.write(`PASS ${label}\n`);};
try{
 for(const name of ["metrics","contracts","governed-sources"]){const source=await readFile(join(root,"lib",name+".ts"),"utf8");const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replaceAll('"./metrics"','"./metrics.mjs"').replaceAll('"./contracts"','"./contracts.mjs"');await writeFile(join(temp,name+".mjs"),code);}
 const {METRICS,calculate,visibleModules,allowedMetrics,scopeSites,validPeriod}=await import(pathToFileURL(join(temp,"metrics.mjs")));
 const {assuranceRows,financeRows,safeFieldValues,extractCandidates,parseDelimited}=await import(pathToFileURL(join(temp,"contracts.mjs")));
 const {governedSources,governedExampleAnswer}=await import(pathToFileURL(join(temp,"governed-sources.mjs")));
 const metric=METRICS.find(m=>m.id==="delivery");
 const observations=[{metric:"delivery",site:"A",period:"2026-09",numerator:90,denominator:100,status:"approved"},{metric:"delivery",site:"B",period:"2026-09",numerator:1,denominator:1,status:"approved"}];
 check("rates weight the raw counts",()=>assert.ok(Math.abs(calculate(metric,observations)-91/101*100)<1e-8));
 check("pending values are excluded",()=>assert.equal(calculate(metric,[...observations,{...observations[0],status:"pending",numerator:999}]),calculate(metric,observations)));
 check("absent data is null",()=>assert.equal(calculate(metric,[]),null));
 check("zero denominator is null",()=>assert.equal(calculate(metric,[{...observations[0],denominator:0}]),null));
 const requirement={id:"R",contractId:"C",status:"approved",metricId:"delivery",target:89,amber:85,type:"Contract",code:"X",title:"Delivery",quote:"Reviewed source"};
 check("contract target overrides company threshold",()=>assert.equal(assuranceRows([requirement],[metric],observations,"A","2026-09")[0].status,"On target"));
 check("assurance uses the selected site",()=>assert.equal(assuranceRows([requirement],[metric],observations,"B","2026-09")[0].value,100));
 check("draft obligations are excluded",()=>assert.equal(assuranceRows([{...requirement,status:"draft"}],[metric],observations,"A","2026-09").length,0));
 check("assurance missing result is explicit",()=>assert.equal(assuranceRows([requirement],[metric],observations,"C","2026-09")[0].status,"No data"));
 const scalar={...metric,id:"median",method:"value"};const scalars=observations.map((o,i)=>({...o,metric:"median",numerator:4+i*2,denominator:1}));
 check("scalar source result is retained",()=>assert.equal(calculate(scalar,scalars.slice(0,1)),4));
 check("medians are not aggregated across sites",()=>assert.equal(calculate(scalar,scalars),null));
 const line={id:"L",site:"A",name:"Staff",type:"cost"};const mapping={accountCode:"400",tracking:"A",site:"A",lineId:"L"};const budget={lineId:"L",site:"A",period:"2026-04",amount:100};const actual={accountCode:"400",tracking:"A",period:"2026-04",amount:110,status:"approved"};
 const finance=(bb=[budget],aa=[actual],mm=[mapping],period="2026-04",ytd=false,ll=[line])=>financeRows(ll,bb,aa,mm,period,"A",ytd);
 check("cost variance is favourable budget minus actual",()=>assert.equal(finance().rows[0].variance,-10));
 check("revenue variance is actual minus budget",()=>assert.equal(finance(undefined,undefined,undefined,undefined,false,[{...line,type:"income"}]).rows[0].variance,10));
 check("pending finance balance is excluded",()=>assert.equal(finance(undefined,[actual,{...actual,status:"pending",amount:999}]).rows[0].actual,110));
 check("missing budget is not zero",()=>assert.equal(finance([]).rows[0].budget,null));
 check("missing actual is not zero",()=>assert.equal(finance(undefined,[]).rows[0].actual,null));
 check("explicit zero actual remains zero",()=>assert.equal(finance(undefined,[{...actual,amount:0}]).rows[0].actual,0));
 check("unmapped balances stay separate",()=>assert.equal(finance(undefined,[actual,{...actual,accountCode:"999"}]).unmapped.length,1));
 check("incomplete mapped accounts suppress total",()=>assert.equal(finance(undefined,undefined,[mapping,{...mapping,accountCode:"401"}]).rows[0].actual,null));
 check("incomplete YTD budget is withheld",()=>assert.equal(finance(undefined,undefined,undefined,"2026-05",true).rows[0].budget,null));
 check("incomplete YTD actual is withheld",()=>assert.equal(finance(undefined,undefined,undefined,"2026-05",true).rows[0].actual,null));
 check("YTD identifies the missing month",()=>assert.deepEqual(finance(undefined,undefined,undefined,"2026-05",true).rows[0].missingActualPeriods,["2026-05"]));
 check("January uses the preceding April financial year",()=>assert.equal(finance(undefined,undefined,undefined,"2027-01",true).rows[0].expectedPeriods[0],"2026-04"));
 check("commissioner has only assurance module",()=>assert.deepEqual(visibleModules("drpa","commissioner"),["assurance"]));
 check("commissioner receives no internal metric catalogue",()=>assert.equal(allowedMetrics("drpa","commissioner").length,0));
 check("commissioner assignment limits the site",()=>assert.deepEqual(scopeSites("drpa","commissioner"),["HMP Bristol"]));
 check("customer example has no financial module",()=>assert.equal(visibleModules("customer","board").includes("finance"),false));
 check("restricted custom metrics remain hidden from site",()=>assert.equal(allowedMetrics("drpa","site",[{...metric,id:"restricted",restricted:true}]).some(m=>m.id==="restricted"),false));
 const field={key:"reason",label:"Reason",type:"choice",options:["Approved"],required:true,metricId:"delivery"};
 check("required custom field is enforced",()=>assert.throws(()=>safeFieldValues([field],"delivery",{})));
 check("choice fields reject unknown options",()=>assert.throws(()=>safeFieldValues([field],"delivery",{reason:"Unknown"})));
 check("unknown extra fields are discarded",()=>assert.deepEqual(safeFieldValues([field],"delivery",{reason:"Approved",unknown:"private"}),{reason:"Approved"}));
 check("extraction never approves a requirement",()=>assert.equal(extractCandidates("KPI 7: Reports must meet a target of 98%.","Contract")[0].status,"draft"));
 check("quoted CSV commas are preserved",()=>assert.equal(parseDelimited('account,reference\n400,"source, reviewed"')[0].reference,"source, reviewed"));
 check("future reporting month is supported",()=>assert.equal(validPeriod("2027-01"),true));
 check("invalid reporting month is rejected",()=>assert.equal(validPeriod("2026-13"),false));
 const contract={id:"C",title:"Reviewed schedule",sites:["A","B"],effectiveFrom:"2026-04-01",effectiveTo:"2027-03-31"};const input={contracts:[contract],requirements:[requirement,{...requirement,id:"draft",status:"draft"}],metrics:[metric],observations,sites:["A"],period:"2026-09",site:"all"};
 check("question context excludes draft/out-of-scope obligations",()=>assert.equal(governedSources(input).length,1));
 check("question context respects contract dates",()=>assert.equal(governedSources({...input,period:"2027-09"}).length,0));
 check("finance question cannot use contract sources",()=>assert.equal(governedExampleAnswer("What is the budget?",governedSources(input)).sources.length,0));
 const source=governedSources({...input,contracts:[],requirements:[],period:"2026-04",site:"A",finance:{lines:[line],budgets:[budget],actuals:[actual,{...actual,status:"pending",amount:999}],mappings:[mapping]}});
 check("finance question uses approved actual only",()=>assert.equal(JSON.parse(source[0].detail).approvedActual,110));
 check("FMT example answer cites the budget source",()=>assert.ok(governedExampleAnswer("What is the FMT variance?",source).content.includes("£110")));
 process.stdout.write(`${count} domain checks passed.\n`);
}finally{await rm(temp,{recursive:true,force:true});}
