import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";
import { database, auditStatement } from "@/lib/store";
import { TENANTS,ROLES,allowedMetrics,visibleModules,scopeSites,type TenantId } from "@/lib/metrics";
export const dynamic="force-dynamic";
const dev=(import.meta as unknown as {env?:{DEV?:boolean}}).env?.DEV===true;
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"no-store"}});
async function authorised(request:Request){const user=await getChatGPTUser();if(!user&&!dev)throw new Error("AUTH");const url=new URL(request.url),tenant=url.searchParams.get("tenant")||"drpa",role=url.searchParams.get("role")||"board";if(!Object.hasOwn(TENANTS,tenant)||!ROLES.some(r=>r.id===role))throw new Error("Invalid scope.");if(!visibleModules(tenant as TenantId,role).includes("evidence"))throw new Error("ACCESS");return {userId:user?.userId||"local-demo-owner",tenant:tenant as TenantId,departments:[...new Set(allowedMetrics(tenant as TenantId,role).map(m=>m.department))],role,url,sites:scopeSites(tenant as TenantId,role)};}
const fail=(e:unknown)=>e instanceof Error&&e.message==="AUTH"?reply({error:"Sign in to access files."},401):e instanceof Error&&e.message==="ACCESS"?reply({error:"Documents are outside your scope."},403):reply({error:e instanceof Error?e.message:"The file request failed."},400);
export async function GET(request:Request){try{const s=await authorised(request);const db=database();const id=s.url.searchParams.get("id");if(id){const file=await db.prepare("SELECT * FROM evidence_documents WHERE id=? AND tenant=?").bind(id,s.tenant).first<{object_key:string;department:string;site:string;mime:string;filename:string}>();if(!file||(!s.departments.includes(file.department)||(file.site==="company"?s.sites.length!==TENANTS[s.tenant].sites.length:!s.sites.includes(file.site))))return reply({error:"File not found in your scope."},404);const object=await env.BUCKET?.get(file.object_key);if(!object)return reply({error:"File storage is unavailable."},503);return new Response(object.body,{headers:{"Content-Type":file.mime,"Content-Disposition":`attachment; filename="${file.filename.replace(/[^a-zA-Z0-9._-]/g,"_")}"`,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});}
 const results=await db.prepare("SELECT id,title,filename,department,site,size,status,created FROM evidence_documents WHERE tenant=? ORDER BY created DESC LIMIT 100").bind(s.tenant).all();return reply({files:results.results.filter(f=>s.departments.includes(f.department as string)&&(f.site==="company"?s.sites.length===TENANTS[s.tenant].sites.length:s.sites.includes(f.site as string)))});}catch(e){return fail(e);}}
export async function POST(request:Request){try{const s=await authorised(request);const origin=request.headers.get("origin");if(origin&&origin!==s.url.origin&&origin!=="https://drpa-intelligence-engine.sa33dc.chatgpt.site"&&!(dev&&origin==="http://terminal.local:4173"))return reply({error:"Origin not permitted."},403);if(!env.BUCKET)throw new Error("File storage is temporarily unavailable.");const length=Number(request.headers.get("content-length")||0);if(length>5500000)return reply({error:"The file must be no larger than 5 MB."},413);
 const form=await request.formData();const recordSite=s.role==="site"?s.sites[0]:String(form.get("site")||"company");if(recordSite!=="company"&&!s.sites.includes(recordSite))throw new Error("This site is outside your scope.");const file=form.get("file"),department=String(form.get("department")||""),title=String(form.get("title")||"").slice(0,150);if(!(file instanceof File)||file.size===0||file.size>5242880)throw new Error("Choose a sample file of 1 byte–5 MB.");if(!s.departments.includes(department))throw new Error("This department is outside your scope.");const ext=file.name.split(".").pop()?.toLowerCase();const types:Record<string,string>={pdf:"application/pdf",docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",xlsx:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",txt:"text/plain",csv:"text/csv"};if(!ext||!types[ext])throw new Error("Use PDF, DOCX, XLSX, TXT or CSV.");const bytes=await file.arrayBuffer();const leading=new Uint8Array(bytes.slice(0,5));if(ext==="pdf"&&new TextDecoder().decode(leading)!=="%PDF-")throw new Error("This file does not have a valid PDF signature.");if((ext==="docx"||ext==="xlsx")&&(leading[0]!==80||leading[1]!==75))throw new Error("This file does not have a valid Office container signature.");
 const id=crypto.randomUUID(),objectKey=`${s.tenant}/pending/${id}.${ext}`,status="Pending extraction & review";await env.BUCKET.put(objectKey,bytes,{httpMetadata:{contentType:types[ext]}});try{await database().batch([database().prepare("INSERT INTO evidence_documents (id,tenant,title,filename,department,site,mime,size,object_key,status,actor,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,s.tenant,title||file.name,file.name.slice(0,200),department,recordSite,types[ext],file.size,objectKey,status,s.userId,new Date().toISOString()),auditStatement(s.tenant,s.userId,"Document uploaded",id,JSON.stringify({filename:file.name,department,site:recordSite,size:file.size,status,rolePreview:s.role}))]);}catch(e){await env.BUCKET.delete(objectKey);throw e;}return reply({file:{id,title:title||file.name,filename:file.name.slice(0,200),department,site:recordSite,size:file.size,status}});
 }catch(e){return fail(e);}}
