import { requestScope, requireModule, sameOrigin, apiFailure } from "@/lib/access";
import { database, auditStatement, seed } from "@/lib/store";
import { listRecords, oneRecord, createRecord, updateRecord, seedAdvanced, type Stored, customMetrics } from "@/lib/records";
import { validPeriod, METRICS, type Metric, type Observation } from "@/lib/metrics";
import { extractCandidates, assuranceRows, FMT_GROUPS, type Contract, type Requirement, type DataField, type AssurancePack, type FmtLine, type Budget, type AccountMapping, type Actual } from "@/lib/contracts";
import referenceLibrary from "@/lib/kpi-reference.json";
import { xeroStatus } from "@/lib/xero";
export const dynamic="force-dynamic";
const reply=(value:unknown,status=200)=>Response.json(value,{status,headers:{"Cache-Control":"no-store"}});
const str=(v:unknown,max=200)=>typeof v==="string"?v.trim().slice(0,max):"";
function required(v:unknown,label:string,max=200){const t=str(v,max);if(!t)throw new Error(`${label} is required.`);return t;}
function numeric(v:unknown,label:string){if(v===""||v===null||v===undefined||!Number.isFinite(Number(v)))throw new Error(`${label} must be a number.`);return Number(v);}
export async function GET(request:Request){try{
 const s=await requestScope(request);if(!s.modules.some(m=>["contracts","finance","assurance","configure"].includes(m)))throw new Error("ACCESS");await seed(s.tenant);await seedAdvanced(s.tenant);
 const packs=(await listRecords<AssurancePack>(s.tenant,"pack")).filter(p=>s.sites.includes(p.site)&& (s.role!=="commissioner"||p.status==="published"));
 if(s.role==="commissioner")return reply({packs,contracts:[],requirements:[],fields:[],lines:[],budgets:[],mappings:[],actuals:[],pendingActuals:[],extracts:[],library:[],xero:null});
 const contracts=(await listRecords<Contract>(s.tenant,"contract")).filter(c=>c.sites.some(x=>s.sites.includes(x)));const allowed=new Set(contracts.map(c=>c.id));
 const requirements=(await listRecords<Requirement>(s.tenant,"requirement")).filter(r=>allowed.has(r.contractId)&&(!r.metricId||s.metrics.some(m=>m.id===r.metricId)));
 const extracts=s.modules.includes("contracts")?(await listRecords<{contractId:string}>(s.tenant,"extract")).filter(x=>allowed.has(x.contractId)):[];
 const fields=(await listRecords<DataField>(s.tenant,"field")).filter(f=>!f.metricId||s.metrics.some(m=>m.id===f.metricId));const canFinance=s.modules.includes("finance");
 return reply({contracts,requirements,fields,packs,extracts,library:s.modules.includes("configure")&&s.tenant==="drpa"?referenceLibrary:[],lines:canFinance?await listRecords<FmtLine>(s.tenant,"fmt_line"):[],budgets:canFinance?await listRecords<Budget>(s.tenant,"budget"):[],mappings:canFinance?await listRecords<AccountMapping>(s.tenant,"mapping"):[],actuals:canFinance?await listRecords<Actual>(s.tenant,"actual"):[],pendingActuals:canFinance?(await listRecords<Actual>(s.tenant,"actual_pending")).filter(a=>a.status==="pending"):[],xero:canFinance?await xeroStatus(s.tenant,s.user.id):null});
 }catch(e){return apiFailure(e);}}
export async function POST(request:Request){try{
 const s=await requestScope(request);sameOrigin(request);if(s.role==="commissioner"||s.role==="contributor")throw new Error("ACCESS");if(!request.headers.get("content-type")?.startsWith("application/json"))throw new Error("JSON input is required.");const text=await request.text();if(text.length>220000)throw new Error("The input is too large.");const b=JSON.parse(text);await seed(s.tenant);await seedAdvanced(s.tenant);const db=database();
 const save=async(kind:string,payload:Record<string,unknown>,id?:string,version?:number)=>{const current=id?await oneRecord(s.tenant,kind,id):null;if(id&&!current)throw new Error("Record not found in this organisation.");if(current&&current._version!==version)throw new Error("A newer version exists. Refresh before saving.");const target=id||crypto.randomUUID();const p={...payload,id:target};const result=await db.batch([current?updateRecord(s.tenant,kind,target,p,version!):createRecord(s.tenant,kind,p,target),auditStatement(s.tenant,s.user.id,`${kind} ${current?'updated':'created'}`,target,JSON.stringify({before:current,after:p,rolePreview:s.role}))]);if(result[0].meta.changes===0)throw new Error("This record changed during your edit. Refresh and try again.");return target;};
 const contractFor=async(id:string)=>{const c=await oneRecord<Contract>(s.tenant,"contract",id);if(!c||!c.sites.some(x=>s.sites.includes(x)))throw new Error("Contract not found in your site scope.");return c;};
 if(b.action==="save_contract"){
  requireModule(s,"contracts");if(s.role!=="board")throw new Error("ACCESS");const sites=Array.isArray(b.sites)?b.sites:[];if(!sites.length||sites.some((x:string)=>!s.sites.includes(x)))throw new Error("Choose permitted contract sites.");const from=required(b.effectiveFrom,"Effective from"),to=required(b.effectiveTo,"Effective to");if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)throw new Error("Use a valid contract date range.");return reply({id:await save("contract",{title:required(b.title,"Contract title"),commissioner:required(b.commissioner,"Commissioner"),service:required(b.service,"Service"),sites,reference:required(b.reference,"Signed source reference",500),version:required(b.version,"Source version"),effectiveFrom:from,effectiveTo:to,status:"Active",note:str(b.note,2000)},b.id,b._version)});
 }
 if(b.action==="extract"){
  requireModule(s,"contracts");await contractFor(b.contractId);const type=["Contract","HJIP","Bid commitment"].includes(b.type)?b.type:"Contract";const content=required(b.text,"Source extract",100000);if(b.documentId){const doc=await db.prepare("SELECT site,department FROM evidence_documents WHERE id=? AND tenant=?").bind(b.documentId,s.tenant).first<{site:string;department:string}>();if(!doc||!s.metrics.some(m=>m.department===doc.department)||doc.site!=="company"&&!s.sites.includes(doc.site)||doc.site==="company"&&s.sites.length<6&&s.tenant==="drpa")throw new Error("Source document is outside your scope.");}
  const id=await save("extract",{contractId:b.contractId,documentId:str(b.documentId),purpose:type,title:required(b.title,"Source title"),sourceVersion:required(b.sourceVersion,"Source version"),text:content,status:"Extracted · requires mapping and approval",created:new Date().toISOString()});if(b.documentId)await db.prepare("UPDATE evidence_documents SET status=? WHERE id=? AND tenant=?").bind("Text extracted · mapping and review pending",b.documentId,s.tenant).run();return reply({id,candidates:extractCandidates(content,type),mode:"text-rules"});
 }
 if(b.action==="save_requirement"){
  requireModule(s,"contracts");if(!["board","clinical","site","bid"].includes(s.role))throw new Error("ACCESS");const c=await contractFor(b.contractId);if(b.id){const current=await oneRecord<Requirement>(s.tenant,"requirement",b.id);if(!current)throw new Error("Requirement not found.");await contractFor(current.contractId);if(s.role==="bid"&&current.status==="approved")throw new Error("Bid developers cannot change an approved obligation.");}const metric=s.metrics.find(m=>m.id===b.metricId);if(!metric)throw new Error("Choose a permitted KPI definition.");const target=numeric(b.target,"Target"),amber=numeric(b.amber,"Amber threshold");if(metric.direction==="high"&&amber>target||metric.direction==="low"&&amber<target)throw new Error("The amber threshold must sit between failure and the target.");if(!["Contract","HJIP","Bid commitment"].includes(b.type))throw new Error("Choose an obligation type.");if(b.status==="approved"&&s.role==="bid")throw new Error("Bid developers can propose commitments but cannot approve them.");if(!c.sites.every(x=>!metric.sites?.length||metric.sites.includes(x)))throw new Error("This metric is not enabled for all contract sites.");
  const p={contractId:c.id,type:b.type,code:required(b.code,"Indicator code"),title:required(b.title,"Indicator title"),clause:required(b.clause,"Clause / sheet / row",500),quote:required(b.quote,"Exact source excerpt",3000),metricId:metric.id,target,amber,frequency:required(b.frequency,"Reporting frequency"),owner:required(b.owner,"Accountable owner"),sourceVersion:required(b.sourceVersion,"Source version"),documentId:str(b.documentId),status:b.status==="approved"?"approved":"draft",attribution:required(b.attribution,"Attribution"),exception:str(b.exception,2000),action:str(b.remedialAction,2000),actionOwner:str(b.actionOwner),dueDate:str(b.dueDate),shareEvidence:str(b.shareEvidence,2000),definitionNote:str(b.definitionNote,2000)};return reply({id:await save("requirement",p,b.id,b._version)});
 }
 if(b.action==="save_metric"){
  requireModule(s,"configure");if(s.role!=="board")throw new Error("ACCESS");const code=required(b.metricId,"Unique measure ID");if(!/^[a-zA-Z0-9_-]{2,60}$/.test(code)||METRICS.some(m=>m.id===code))throw new Error("Use a unique ID containing letters, numbers, underscores or hyphens.");const all=await customMetrics(s.tenant);if(all.some(m=>m.id===code))throw new Error("That ID exists. A changed definition needs a new version ID to preserve history.");if(!["sum","ratio","mean","rate","value"].includes(b.method)||!["high","low"].includes(b.direction))throw new Error("Choose a supported calculation and direction.");const department=required(b.department,"Department");if(![...new Set(METRICS.map(m=>m.department))].includes(department))throw new Error("Choose a recognised department.");const target=numeric(b.target,"Target"),amber=numeric(b.amber,"Amber threshold");if(b.direction==="high"&&amber>target||b.direction==="low"&&amber<target)throw new Error("Check the target and amber thresholds.");const sites=Array.isArray(b.sites)?b.sites:s.sites;if(!sites.length||sites.some((x:string)=>!s.sites.includes(x)))throw new Error("Choose permitted sites.");const p={name:required(b.name,"Measure name"),department,owner:required(b.owner,"Owner"),unit:required(b.unit,"Unit"),method:b.method,direction:b.direction,target,amber,numeratorLabel:required(b.numeratorLabel,"Numerator"),denominatorLabel:required(b.denominatorLabel,"Denominator"),source:required(b.source,"Source",500),decision:required(b.decision,"Definition and supported decision",2000),restricted:department==="Finance"||!!b.restricted,sites,definitionVersion:required(b.definitionVersion,"Definition version")};await db.batch([createRecord(s.tenant,"metric",{...p,id:code},code+"@"+s.tenant),auditStatement(s.tenant,s.user.id,"Metric definition activated",code,JSON.stringify({definition:p,rolePreview:s.role}))]);return reply({ok:true,id:code});
 }
 if(b.action==="save_field"){
  requireModule(s,"configure");const key=required(b.key,"Field key");if(!/^[a-z][a-z0-9_]{1,39}$/.test(key))throw new Error("Use a lowercase key with underscores.");const fields=await listRecords<DataField>(s.tenant,"field");if(fields.some(f=>f.key===key))throw new Error("This field key already exists.");if(!["text","number","date","choice"].includes(b.type))throw new Error("Choose a field type.");if(b.metricId&&!s.metrics.some(m=>m.id===b.metricId))throw new Error("Choose a permitted KPI.");const options=Array.isArray(b.options)?b.options.map((x:unknown)=>str(x,100)).filter(Boolean).slice(0,30):[];if(b.type==="choice"&&!options.length)throw new Error("Provide the permitted choices.");return reply({id:await save("field",{key,label:required(b.label,"Field label"),metricId:str(b.metricId),type:b.type,options,required:!!b.required})});
 }
 if(["save_fmt_line","save_budget","save_mapping","import_actuals","approve_actuals"].includes(b.action)){
  requireModule(s,"finance");if(!["board","finance"].includes(s.role))throw new Error("ACCESS");
  if(b.action==="save_fmt_line"){if(!s.sites.includes(b.site)||!FMT_GROUPS.includes(b.group)||!["income","cost"].includes(b.type))throw new Error("Choose a permitted site, FMT group and line type.");return reply({id:await save("fmt_line",{site:b.site,service:required(b.service,"Service"),group:b.group,name:required(b.name,"FMT line name"),type:b.type,reference:required(b.reference,"FMT cell / row reference",500),baselineVersion:required(b.baselineVersion,"Approved FMT version")},b.id,b._version)});}
  const lines=await listRecords<FmtLine>(s.tenant,"fmt_line");
  if(b.action==="save_budget"){const line=lines.find(l=>l.id===b.lineId);if(!line||!s.sites.includes(line.site)||!validPeriod(b.period))throw new Error("Choose a permitted FMT line and month.");const existing=(await listRecords<Budget>(s.tenant,"budget")).find(x=>x.lineId===line.id&&x.period===b.period);const id=await save("budget",{lineId:line.id,site:line.site,period:b.period,amount:numeric(b.amount,"Budget"),source:required(b.source,"Budget source reference",500)},existing?.id,existing?b._version:undefined);return reply({id});}
  if(b.action==="save_mapping"){const line=lines.find(l=>l.id===b.lineId);if(!line||!s.sites.includes(line.site))throw new Error("Choose a permitted FMT line.");const accountCode=required(b.accountCode,"Xero account code",80),tracking=required(b.tracking,"Exact tracking option",200);const existing=(await listRecords<AccountMapping>(s.tenant,"mapping")).find(x=>x.accountCode===accountCode&&x.tracking===tracking);return reply({id:await save("mapping",{accountCode,tracking,lineId:line.id,site:line.site},existing?.id,existing?b._version:undefined)});}
  if(b.action==="import_actuals"){
   const rows=Array.isArray(b.records)?b.records:[];if(!rows.length||rows.length>100)throw new Error("Import between 1 and 100 account-period rows.");const statements:D1PreparedStatement[]=[];const keys=new Set<string>();
   for(const r of rows){if(!validPeriod(r.period))throw new Error("Choose an available reporting month.");const accountCode=required(r.accountCode,"Account code",80),tracking=required(r.tracking,"Tracking option; use UNALLOCATED if missing"),grain=[s.tenant,accountCode,tracking,r.period].join("|");if(keys.has(grain))throw new Error("The import repeats an account / tracking / month. Combine it into one balance.");keys.add(grain);const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(grain));const found=await db.prepare("SELECT id FROM platform_records WHERE tenant=? AND kind='actual' AND json_extract(payload,'$.accountCode')=? AND json_extract(payload,'$.tracking')=? AND json_extract(payload,'$.period')=?").bind(s.tenant,accountCode,tracking,r.period).first<{id:string}>();const targetId=found?.id||"ledger-"+Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,"0")).join("");const old=await oneRecord(s.tenant,"actual",targetId);const id=crypto.randomUUID();const p={id,targetId,baseVersion:old?._version||0,accountCode,accountName:required(r.accountName,"Account name"),tracking,period:r.period,amount:numeric(r.amount,"Actual amount"),reference:required(r.reference,"Account balance source reference",500),status:"pending",source:"CSV account-period import",created:new Date().toISOString()};statements.push(db.prepare("UPDATE platform_records SET payload=json_set(payload,'$.status','superseded'),version=version+1,updated=? WHERE tenant=? AND kind='actual_pending' AND json_extract(payload,'$.targetId')=? AND json_extract(payload,'$.status')='pending'").bind(new Date().toISOString(),s.tenant,targetId));statements.push(createRecord(s.tenant,"actual_pending",p,id));}
   statements.push(auditStatement(s.tenant,s.user.id,"Ledger import staged",crypto.randomUUID(),JSON.stringify({rows:rows.length,rolePreview:s.role})));await db.batch(statements);return reply({ok:true,count:rows.length});
  }
  if(b.action==="approve_actuals"){
   const ids=Array.isArray(b.ids)?b.ids:[];if(!ids.length||ids.length>100)throw new Error("Review between 1 and 100 staged balances.");let approved=0;
   for(const id of ids){const draft=await oneRecord<Actual&{targetId:string;baseVersion:number}>(s.tenant,"actual_pending",id);if(!draft||draft.status!=="pending")throw new Error("Staged balance no longer exists or has been superseded.");const old=await oneRecord(s.tenant,"actual",draft.targetId);if((old?._version||0)!==draft.baseVersion)throw new Error("An approved balance changed after this import. Import the latest balance again.");const approvalId=crypto.randomUUID(),{_version,targetId,baseVersion,...rest}=draft;const p={...rest,id:targetId,status:"approved",approvalId};const result=await db.batch([old?updateRecord(s.tenant,"actual",targetId,p,old._version):database().prepare("INSERT OR IGNORE INTO platform_records (id,tenant,kind,payload,version,created,updated) VALUES (?,?,'actual',?,1,?,?)").bind(targetId,s.tenant,JSON.stringify(p),new Date().toISOString(),new Date().toISOString()),database().prepare("DELETE FROM platform_records WHERE id=? AND tenant=? AND kind='actual_pending' AND EXISTS (SELECT 1 FROM platform_records WHERE id=? AND tenant=? AND kind='actual' AND json_extract(payload,'$.approvalId')=?)").bind(id,s.tenant,targetId,s.tenant,approvalId)]);if(result[1].meta.changes===0)throw new Error("A simultaneous review changed this balance. Refresh and re-import.");approved++;await db.batch([auditStatement(s.tenant,s.user.id,"Ledger balance approved",targetId,JSON.stringify({before:old,after:p,rolePreview:s.role}))]);}return reply({ok:true,count:approved});
  }
 }
 if(b.action==="prepare_pack"){
  requireModule(s,"assurance");if(!["board","clinical","site"].includes(s.role))throw new Error("ACCESS");const c=await contractFor(b.contractId);if(!c.sites.includes(b.site)||!s.sites.includes(b.site)||!validPeriod(b.period))throw new Error("Choose a permitted site and month.");if(b.period<c.effectiveFrom.slice(0,7)||b.period>c.effectiveTo.slice(0,7))throw new Error("The reporting month is outside the contract effective dates.");const ids=Array.isArray(b.requirementIds)?b.requirementIds:[];const req=(await listRecords<Requirement>(s.tenant,"requirement")).filter(r=>r.contractId===c.id&&r.status==="approved"&&ids.includes(r.id)&&s.metrics.some(m=>m.id===r.metricId));if(!req.length||req.length!==new Set(ids).size)throw new Error("Select approved obligations in your scope.");const observations=(await db.prepare("SELECT * FROM observations WHERE tenant=? AND site=? AND period=? AND status='approved'").bind(s.tenant,b.site,b.period).all<Observation>()).results;const previous=(await listRecords<AssurancePack>(s.tenant,"pack")).filter(p=>p.contractId===c.id&&p.site===b.site&&p.period===b.period);const id=crypto.randomUUID();const p={id,contractId:c.id,contractTitle:c.title,commissioner:c.commissioner,site:b.site,period:b.period,title:required(b.title,"Pack title"),summary:required(b.summary,"Reviewed summary and limitations",3000),rows:assuranceRows(req,s.metrics,observations,b.site,b.period),includedCount:req.length,totalCount:(await listRecords<Requirement>(s.tenant,"requirement")).filter(r=>r.contractId===c.id&&r.status==="approved"&&s.metrics.some(m=>m.id===r.metricId)).length,status:"draft",version:Math.max(0,...previous.map(x=>x.version))+1,created:new Date().toISOString(),publishedAt:"",approvedBy:"",dataAsOf:observations.reduce((v,o)=>o.updated>v?o.updated:v,""),synthetic:true};await db.batch([createRecord(s.tenant,"pack",p,id),auditStatement(s.tenant,s.user.id,"Assurance pack prepared",id,JSON.stringify({site:b.site,period:b.period,contractId:c.id,requirementIds:ids,rolePreview:s.role}))]);return reply({ok:true,id});
 }
 if(b.action==="publish_pack"){
  requireModule(s,"assurance");if(!["board","clinical"].includes(s.role)||b.attested!==true)throw new Error("A director or clinical reviewer must approve the sharing statement.");const p=await oneRecord<AssurancePack>(s.tenant,"pack",b.id);if(!p||!s.sites.includes(p.site)||p.status!=="draft")throw new Error("Draft pack not found in your scope.");if(p.rows.some(r=>["Action","No data"].includes(r.status)&&(!r.action||!r.actionOwner||!r.dueDate)))throw new Error("Every action-level exception or missing result needs an action, owner and due date before publication.");const { _version,...clean}=p;const updated={...clean,status:"published",publishedAt:new Date().toISOString(),approvedBy:s.user.name};const result=await db.batch([updateRecord(s.tenant,"pack",p.id,updated,_version),auditStatement(s.tenant,s.user.id,"Assurance pack published",p.id,JSON.stringify({site:p.site,period:p.period,contractId:p.contractId,version:p.version,rolePreview:s.role}))]);if(result[0].meta.changes===0)throw new Error("This pack changed. Refresh before publishing.");return reply({ok:true});
 }
 throw new Error("Unknown action.");
 }catch(e){return apiFailure(e);}}
